### ISSUE TITLE
Light - Regulation: Research how to regulate light, ideal instrument to use and if it can be controlled

### ISSUE THREAD

**Issue by isombeg** [Plant-Monitor/Plant-Monitor-Device#3]

**Comment by isombeg** [comment]
@Ajimokas is this good to close?

**Comment by Ajimokas** [comment]
Light Research


Questions: did we decide that we’re using artificial light, like the final design will include a portion of light bulbs?


Since, this is a project for individual plants and not large greenhouses, there is no way we can possibly control sunlight from reducing its intensity, however, we can detect levels of intensity and alert the owner if it’s too intense or not intense enough.

 We can measure sunlight using LUX, Lux is a standard measure of light intensity. A measurement of 1 lux is equal to the illumination of a one metre square surface that is one metre away from a single candle. This also means 1 lux = 1 lumen per square meter. The more lumens, the brighter the light is in a specific area. Plants need about 7000 to 7500  lumens of light to prosper as indoor plants 

We can use three things

Grove sunlight Sensor 
https://taylor.callsen.me/the-smart-shoe-a-raspberry-pi-sunlight-sensor/
	- Can track UV and IR light that the plant gets sent 
	issues include: price of raspberry pi 3, wait times to test (shipping from the states), 

LDR circuit
https://www.instructables.com/Measuring-Light-Using-Light-Sensor/
	- LDR photoresists with Arduino 
	- Cheap and easy to implement with Arduino 
	issues include: might not be as accurate at determining which is sunlight and artificial light which can affect plant growth 


Adafruit sensor
- https://www.instructables.com/How-to-Measure-LUX-With-Arduino/
 - Very precise
- Can detect light ranges from up to 0.1 - 40,000+ Lux on the fly.
- Can separately measure IR, full-spectrum and human visible  light

I suggest the Adafruit sensor as it is capable of achieving all our goals with specificity at a low cost

**Comment by Ajimokas** [comment]
@timiagiri Can you look over the options we have above + your own research for light sensors to decide on what we should use? Thanks

**Comment by timiagiri** [comment]
I went with the Adafruit one; I was able to find some in stock on Digikey so that's good!

**Comment by isombeg** [comment]
Can we close this?

**Comment by timiagiri** [comment]
Yes! I'll close it now
